repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        args:
          - "--pretty"
        additional_dependencies:
          - "selenium==4.11.2"
          - "tqdm==4.65.0"
          - "pydantic==2.1.1"
          - "types-pyyaml==6.0.12.11"
          - "types-tqdm==4.65.0.2"
          - "email-validator==2.0.0.post2"
