version: "3"

services:
  chrome:
    build:
      context: .
      dockerfile: Dockerfile.chrome
    expose:
      - 4444
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - chrome
    volumes:
      - ./automsr.docker.cfg:/app/automsr.cfg
      - ./credentials.json:/app/credentials.json
    environment:
      - AUTOMSR_OPTS=