version: "3"

services:

  selenium:
    image: selenium/standalone-chrome:89.0
    restart: always
    container_name: selenium
    ports:
      - "4444:4444"

  python:
    build: .
    container_name: python
    volumes:
      - ./credentials.json:/app/credentials.json
      - ./setup.cfg:/app/setup.cfg
    depends_on:
      - selenium
