name: Linters

on: [push, pull_request]

jobs:
  linters:
    name: linters hook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install tox
      - run: tox -e linters
